spring:
  application:
    name: kafka_streams
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.bhuvanesh.kafka_streams.deserializer;
